### ISSUE TITLE
Flagging one unhandled err but not another

### ISSUE THREAD

**Issue by grkuntzmd** [GoASTScanner/gas#111] opened 2017-01-12 15:32 UTC
`gas` is flagging this
```
defer func() {
	_ = file.Close()
}()
```
```
Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > _ = file.Close()
```

but not this
```
defer func() {
	_ = req.Body.Close()
}()
```

**Comment by gcmurphy** [comment] 2017-01-12 16:25
Would you be able to provide a more complete example? I tried to reproduce with the following and didn't have any luck. 


```go 
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
)

func main() {

	resp, err := http.Get("http://example.com/")
	if err != nil {
		os.Exit(1)
	}

	defer func() {
		_ = resp.Body.Close()
	}()

	if body, err := ioutil.ReadAll(resp.Body); err == nil {
		fmt.Printf("%s", body)
	}

}
```

```zsh
github.com/GoAstScanner/gas  master ✔                                                                                                                                                             21h56m  
▶ ./gas ~/samples/errors_sample4.go
[gas] 2017/01/12 08:22:00 scanning "/Users/gm/samples/errors_sample4.go"
Results:

[/Users/gm/samples/errors_sample4.go:18] - Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > _ = resp.Body.Close()


Summary:
   Files: 1
   Lines: 25
   Nosec: 0
  Issues: 1

github.com/GoAstScanner/gas  master ✔                                                                                                                                                            21h56m  ⍉
▶ go version
go version go1.7.4 darwin/amd64


```

**Comment by grkuntzmd** [comment] 2017-01-12 16:40
This file fails to give an error:
```
package controllers

import (
	"net/http"

	"github.com/gorilla/mux"
)

func Get() http.HandlerFunc {
	return func(res http.ResponseWriter, req *http.Request) {
		foo := mux.Vars(req)["bar"]
	}
}

func Put() http.HandlerFunc {
	return func(res http.ResponseWriter, req *http.Request) {
		defer func() {
			_ = req.Body.Close()
		}()
	}
}
```

**Comment by gcmurphy** [comment] 2017-01-13 18:12
In this case it won't report an error because the file won't compile as valid Go (due to foo being declared and not used). 

```zsh

github.com/GoAstScanner/gas  master ✔                                                                                                                                                                 1d  
▶ go build ~/samples/controllers/issue111.go                
# command-line-arguments
/Users/gm/samples/controllers/issue111.go:11: foo declared and not used

github.com/GoAstScanner/gas  master ✔                                                                                                                                                                1d  ⍉
▶ gsed -i 's/foo :=/_ =/' ~/samples/controllers/issue111.go 

github.com/GoAstScanner/gas  master ✔                                                                                                                                                                 1d  
▶ go build ~/samples/controllers/issue111.go               

github.com/GoAstScanner/gas  master ✔                                                                                                                                                                 1d  
▶ ./gas ~/samples/controllers/issue111.go                  
[gas] 2017/01/13 10:06:33 scanning "/Users/gm/samples/controllers/issue111.go"
Results:

[/Users/gm/samples/controllers/issue111.go:18] - Errors unhandled. (Confidence: HIGH, Severity: LOW)
  > _ = req.Body.Close()


Summary:
   Files: 1
   Lines: 21
   Nosec: 0
  Issues: 1

```

Gas shouldn't quietly swallow that error so I'll try to get better error reporting in there.

**Comment by gcmurphy** [comment] 2017-01-13 22:02
I believe this rule is behaving correctly here. I've added better reporting around failed compilation: 

```zsh 

[gas] 2017/01/13 14:00:05 Processing "/Users/gm/samples/controllers/issue111.go"...
[gas] 2017/01/13 14:00:05 Failed to process: "/Users/gm/samples/controllers/issue111.go"
[gas] 2017/01/13 14:00:05 Error during type checking: "/Users/gm/samples/controllers/issue111.go:11:3: foo declared but not used"
[gas] 2017/01/13 14:00:05 Halting execution.

```

Closing this for now. Please let me know if you find a case where this is not working as expected.

**Closed by gcmurphy** 2017-01-13 22:02 UTC
