### ISSUE TITLE
No recursive scan

### ISSUE THREAD

**Issue by vtiwari-ring** [GoASTScanner/gas#197] opened 2018-03-30 23:11 UTC
### Summary 
When I run gas with any golang project, it doesn't look into subdirectories for go files rather it scans only the files found in root directory.

### Steps to reproduce the behavior
Make sure there is only one or no go files in your root directory and run the following command;

$gas -fmt=json -out=gasresult.json go/src/github.com/gitorg/mycoderepo

Now, if you had go files in root directory, gas would scan those but it wouldn't care to navigate into subdirectories to find and scan other go files. 
### Gas version
Built latest from master branch
### Go version (output of 'go version')
go version go1.9.2 darwin/amd64
### Operating system / Environment
Mac OSX High Sierra
### Expected behavior
Gas should search all directories for go files and scan those
### Actual behavior
Just scanning files in root directories.

**Comment by gcmurphy** [comment] 2018-04-03 23:58
This is a duplicate of https://github.com/GoASTScanner/gas/issues/184.

**Closed by gcmurphy** 2018-04-03 23:58 UTC
Labels: duplicate
